<?php

use yii\db\Migration;

class m170425_132300_country extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        // Owner
        $this->createTable('country', [
            'country_id' => $this->primaryKey(),
            'country_name_en' => $this->string(100)->notNull(),
            'country_name_ar' => $this->string(100),
            'country_nationality_name_en' => $this->string(100)->notNull(),
            'country_nationality_name_ar' => $this->string(100),
        ], $tableOptions);

        Yii::$app->db->createCommand("INSERT INTO `country` (`country_id`, `country_name_en`, `country_name_ar`, `country_nationality_name_en`, `country_nationality_name_ar`) VALUES
            (1, 'Afghanistan', 'أفغانستان', 'Afghan', 'الأفغاني'),
            (2, 'Albania', 'ألبانيا', 'Albanian', 'الألبانية'),
            (3, 'Algeria', 'الجزائر', 'Algerian', 'جزائري'),
            (4, 'Andorra', 'أندورا', 'Andorran', 'أندورا'),
            (5, 'Angola', 'أنغولا', 'Angolan', 'الأنغولية'),
            (6, 'Argentina', 'الأرجنتين', 'Argentinian', 'الأرجنتيني'),
            (7, 'Armenia', 'أرمينيا', 'Armenian', 'الأرميني'),
            (8, 'Australia', 'أستراليا', 'Australian', 'الأسترالي'),
            (9, 'Austria', 'النمسا', 'Austrian', 'النمساوي'),
            (10, 'Azerbaijan', 'أذربيجان', 'Azerbaijani', 'أذربيجان'),
            (11, 'Bahamas', 'جزر البهاما', 'Bahamian', 'جزر البهاما'),
            (12, 'Bahrain', 'مملكة البحرين', 'Bahraini', 'البحريني'),
            (13, 'Bangladesh', 'بنغلاديش', 'Bangladeshi', 'بنجلاديش'),
            (14, 'Barbados', 'بربادوس', 'Barbadian', 'باربادوسي'),
            (15, 'Belarus', 'روسيا البيضاء', 'Belarusian', 'البيلاروسية'),
            (16, 'Belgium', 'بلجيكا', 'Belgian', 'بلجيكي'),
            (17, 'Belize', 'بليز', 'Belizean', 'بليز'),
            (18, 'Benin', 'بنين', 'Beninese', 'بنين'),
            (19, 'Bhutan', 'بوتان', 'Bhutanese', 'بوتان'),
            (20, 'Bolivia', 'بوليفيا', 'Bolivian', 'بوليفي'),
            (21, 'Bosnia-Herzegovina', 'البوسنة والهرسك', 'Bosnian', 'البوسنية'),
            (22, 'Botswana', 'بوتسوانا', 'Botswanan', 'بوتسوانا'),
            (23, 'Brazil', 'من البرازيل', 'Brazilian', 'برازيلي'),
            (24, 'Britain', 'بريطانيا', 'British', 'البريطانيون'),
            (25, 'Brunei', 'بروناي', 'Bruneian', 'بروناى'),
            (26, 'Bulgaria', 'بلغاريا', 'Bulgarian', 'البلغارية'),
            (27, 'Burkina', 'فاسو', 'Burkinese', 'البوركينية'),
            (28, 'Burma (official name Myanmar)', 'بورما (الاسم الرسمي ميانمار)', 'Burmese', 'البورمي'),
            (29, 'Burundi', 'بوروندي', 'Burundian', 'بوروندي'),
            (30, 'Cambodia', 'كمبوديا', 'Cambodian', 'كمبوديا'),
            (31, 'Cameroon', 'الكاميرون', 'Cameroonian', 'الكاميروني'),
            (32, 'Canada', 'كندا', 'Canadian', 'الكندية'),
            (33, 'Cape Verde Islands', 'جزر الرأس الأخضر', 'Cape Verdean', 'الرأس الأخضر'),
            (34, 'Chad', 'تشاد', 'Chadian', 'التشادية'),
            (35, 'Chile', 'تشيلي', 'Chilean', 'شيلي'),
            (36, 'China', 'الصين', 'Chinese', 'الصينية'),
            (37, 'Colombia', 'كولومبيا', 'Colombian', 'كولومبي'),
            (38, 'Congo', 'الكونغو', 'Congolese', 'الكونغوليين'),
            (39, 'Costa Rica', 'كوستا ريكا', 'Costa Rican', 'كوستاريكا'),
            (40, 'Croatia', 'كرواتيا', 'Croat', 'الكرواتي'),
            (41, 'Cuba', 'كوبا', 'Cuban', 'الكوبية'),
            (42, 'Cyprus', 'قبرص', 'Cypriot', 'القبرصي'),
            (43, 'Czech Republic', 'جمهورية التشيك', 'Czech', 'تشيكي'),
            (44, 'Denmark', 'الدنمارك', 'Danish', 'دانماركي'),
            (45, 'Djibouti', 'جيبوتي', 'Djiboutian', 'جيبوتي'),
            (46, 'Dominica', 'دومينيكا', 'Dominican', 'الدومينيكان'),
            (47, 'Dominican Republic', 'جمهورية الدومينيكان', 'Dominican', 'الدومينيكان'),
            (48, 'Ecuador', 'الإكوادور', 'Ecuadorean', 'الاكوادور'),
            (49, 'Egypt', 'مصر', 'Egyptian', 'مصري'),
            (50, 'El Salvador', 'السلفادور', 'Salvadorean', 'السلفادورية'),
            (51, 'England', 'انجلترا', 'English', 'اللغة الانكليزية'),
            (52, 'Eritrea', 'إريتريا', 'Eritrean', 'الإريترية'),
            (53, 'Estonia', 'استونيا', 'Estonian', 'الإستونية'),
            (54, 'Ethiopia', 'أثيوبيا', 'Ethiopian', 'حبشي'),
            (55, 'Fiji', 'فيجي', 'Fijian', 'الفيجية'),
            (56, 'Finland', 'فنلندا', 'Finnish', 'اللغة الفنلندية'),
            (57, 'France', 'فرنسا', 'French', 'لغة فرنسية'),
            (58, 'Gabon', 'الغابون', 'Gabonese', 'الجابون'),
            (59, 'Gambia, the', 'غامبيا، ل', 'Gambian', 'غامبي'),
            (60, 'Georgia', 'جورجيا', 'Georgian', 'الجورجية'),
            (61, 'Germany', 'ألمانيا', 'German', 'ألماني'),
            (62, 'Ghana', 'غانا', 'Ghanaian', 'الغاني'),
            (63, 'Greece', 'يونان', 'Greek', 'اللغة اليونانية'),
            (64, 'Grenada', 'غرينادا', 'Grenadian', 'جرينادا'),
            (65, 'Guatemala', 'غواتيمالا', 'Guatemalan', 'غواتيمالا'),
            (66, 'Guinea', 'غينيا', 'Guinean', 'الغينية'),
            (67, 'Guyana', 'غيانا', 'Guyanese', 'جويانا'),
            (68, 'Haiti', 'هايتي', 'Haitian', 'هايتي'),
            (69, 'Holland (also Netherlands)', 'هولندا (هولندا أيضا)', 'Dutch', 'اللغة الهولندية'),
            (70, 'Honduras', 'هندوراس', 'Honduran', 'هندوراس'),
            (71, 'Hungary', 'هنغاريا', 'Hungarian', 'الهنغارية'),
            (72, 'Iceland', 'أيسلندا', 'Icelandic', 'أيسلندي'),
            (73, 'India', 'الهند', 'Indian', 'هندي'),
            (74, 'Indonesia', 'أندونيسيا', 'Indonesian', 'الأندونيسية'),
            (75, 'Iran', 'إيران', 'Iranian', 'إيراني'),
            (76, 'Iraq', 'العراق', 'Iraqi', 'عراقي'),
            (77, 'Ireland, Republic of', 'ايرلندا، جمهورية', 'Irish', 'الإيرلنديون'),
            (78, 'Italy', 'إيطاليا', 'Italian', 'الإيطالي'),
            (79, 'Jamaica', 'جامايكا', 'Jamaican', 'الجامايكي'),
            (80, 'Japan', 'اليابان', 'Japanese', 'اللغة اليابانية'),
            (81, 'Jordan', 'الأردن', 'Jordanian', 'أردني'),
            (82, 'Kazakhstan', 'كازاخستان', 'Kazakh', 'الكازاخستاني'),
            (83, 'Kenya', 'كينيا', 'Kenyan', 'الكيني'),
            (84, 'Kuwait', 'مدينة الكويت', 'Kuwaiti', 'كويتي'),
            (85, 'Laos', 'لاوس', 'Laotian', 'اللاوسي'),
            (86, 'Latvia', 'لاتفيا', 'Latvian', 'اللاتفية'),
            (87, 'Lebanon', 'لبنان', 'Lebanese', 'لبناني'),
            (88, 'Liberia', 'ليبيريا', 'Liberian', 'ليبيريا'),
            (89, 'Libya', 'ليبيا', 'Libyan', 'ليبي'),
            (91, 'Lithuania', 'ليتوانيا', 'Lithuanian', 'اللتوانية'),
            (93, 'Macedonia', 'مقدونيا', 'Macedonian', 'المقدونية'),
            (94, 'Madagascar', 'مدغشقر', 'Madagascan', 'مدغشقر'),
            (95, 'Malawi', 'ملاوي', 'Malawian', 'مالاوى'),
            (96, 'Malaysia', 'ماليزيا', 'Malaysian', 'الماليزي'),
            (97, 'Maldives', 'جزر المالديف', 'Maldivian', 'المالديف'),
            (98, 'Mali', 'مالي', 'Malian', 'مالي'),
            (99, 'Malta', 'مالطا', 'Maltese', 'المالطية'),
            (100, 'Mauritania', 'موريتانيا', 'Mauritanian', 'الموريتاني'),
            (101, 'Mauritius', 'موريشيوس', 'Mauritian', 'موريشيوس'),
            (102, 'Mexico', 'المكسيك', 'Mexican', 'المكسيكي'),
            (103, 'Moldova', 'مولدوفا', 'Moldovan', 'مولدوفا'),
            (104, 'Monaco', 'موناكو', 'Monacan', 'موناكو'),
            (105, 'Mongolia', 'منغوليا', 'Mongolian', 'المنغولية'),
            (106, 'Montenegro', 'الجبل الأسود', 'Montenegrin', 'الجبل الأسود'),
            (107, 'Morocco', 'بلاد المغرب', 'Moroccan', 'مغربي'),
            (108, 'Mozambique', 'موزمبيق', 'Mozambican', 'موزمبيق'),
            (110, 'Namibia', 'ناميبيا', 'Namibian', 'الناميبي'),
            (111, 'Nepal', 'نيبال', 'Nepalese', 'النيبالي'),
            (112, 'Netherlands, the (see Holland)', 'هولندا، و(انظر هولندا)', 'Dutch', 'اللغة الهولندية'),
            (113, 'New Zealand', 'نيوزيلندا', 'New Zealand', 'نيوزيلندا'),
            (114, 'Nicaragua', 'نيكاراغوا', 'Nicaraguan', 'نيكاراغوا'),
            (115, 'Niger', 'النيجر', 'Nigerien', 'النيجر'),
            (116, 'Nigeria', 'نيجيريا', 'Nigerian', 'النيجيري'),
            (117, 'North Korea', 'كوريا الشمالية', 'North Korean', 'كوريا الشمالية'),
            (118, 'Norway', 'النرويج', 'Norwegian', 'النرويجية'),
            (119, 'Oman', 'يا شيخ', 'Omani', 'العماني'),
            (120, 'Pakistan', 'باكستان', 'Pakistani', 'باكستاني'),
            (121, 'Panama', 'بناما', 'Panamanian', 'بنمية'),
            (122, 'Papua New Guinea', 'بابوا غينيا الجديدة', 'Guinean', 'الغينية'),
            (123, 'Paraguay', 'باراغواي', 'Paraguayan', 'باراغواي'),
            (124, 'Peru', 'بيرو', 'Peruvian', 'بيرو'),
            (125, 'the Philippines', 'الفلبين', 'Philippine', 'الفلبين'),
            (126, 'Poland', 'بولندا', 'Polish', 'البولندية'),
            (127, 'Portugal', 'البرتغال', 'Portuguese', 'اللغة البرتغالية'),
            (128, 'Qatar', 'دولة قطر', 'Qatari', 'قطري'),
            (129, 'Romania', 'رومانيا', 'Romanian', 'الرومانية'),
            (130, 'Russia', 'روسيا', 'Russian', 'الروسية'),
            (131, 'Rwanda', 'رواندا', 'Rwandan', 'رواندا'),
            (132, 'Saudi Arabia', 'المملكة العربية السعودية', 'Saudi', 'سعودي'),
            (133, 'Scotland', 'أسكتلندا', 'Scottish', 'الاسكتلندي'),
            (134, 'Senegal', 'السنغال', 'Senegalese', 'سنغالي'),
            (135, 'Serbia', 'صربيا', 'Serb or Serbian', 'الصربية أو الصربية'),
            (136, 'Seychelles, the', 'سيشيل، ل', 'Seychellois', 'سيشل'),
            (137, 'Sierra Leone', 'سيرا ليون', 'Sierra Leonian', 'السيراليوني'),
            (138, 'Singapore', 'سنغافورة', 'Singaporean', 'سنغافورة'),
            (139, 'Slovakia', 'سلوفاكيا', 'Slovak', 'السلوفاكية'),
            (140, 'Slovenia', 'سلوفينيا', 'Slovenian', 'سلوفيني'),
            (142, 'Somalia', 'الصومال', 'Somali', 'الصومالية'),
            (143, 'South Africa', 'جنوب أفريقيا', 'South African', 'جنوب أفريقيا'),
            (144, 'South Korea', 'كوريا الجنوبية', 'South Korean', 'كوريا الجنوبية'),
            (145, 'Spain', 'إسبانيا', 'Spanish', 'اللغة الاسبانية'),
            (146, 'Sri Lanka', 'سيريلانكا', 'Sri Lankan', 'سري لانكا'),
            (147, 'Sudan', 'سودان', 'Sudanese', 'سوداني'),
            (148, 'Suriname', 'سورينام', 'Surinamese', 'سورينامي'),
            (149, 'Swaziland', 'سوازيلاند', 'Swazi', 'سوازي'),
            (150, 'Sweden', 'السويد', 'Swedish', 'اللغة السويدية'),
            (151, 'Switzerland', 'سويسرا', 'Swiss', 'سويسري'),
            (152, 'Syria', 'سوريا', 'Syrian', 'سوري'),
            (153, 'Taiwan', 'تايوان', 'Taiwanese', 'تايوانية'),
            (154, 'Tajikistan', 'طاجيكستان', 'Tadjik', 'الطاجيك'),
            (155, 'Tanzania', 'تنزانيا', 'Tanzanian', 'تنزانية'),
            (156, 'Thailand', 'تايلاند', 'Thai', 'التايلاندية'),
            (157, 'Togo', 'توغو', 'Togolese', 'توغو'),
            (158, 'Trinidad and Tobago', 'ترينداد وتوباغو', 'Trinidadian', 'ترينيداد'),
            (159, 'Tobagonian', 'Tobagonian', 'Trinidadian', 'ترينيداد'),
            (160, 'Tunisia', 'تونس', 'Tunisian', 'التونسية'),
            (161, 'Turkey', 'الديك الرومي', 'Turkish', 'اللغة التركية'),
            (162, 'Turkmenistan', 'تركمانستان', 'Turkmen', 'التركمان'),
            (163, 'Tuvalu', 'توفالو', 'Tuvaluan', 'التوفالية'),
            (164, 'Uganda', 'أوغندا', 'Ugandan', 'الأوغندي'),
            (165, 'Ukraine', 'أوكرانيا', 'Ukrainian', 'الأوكراني'),
            (166, 'United Arab Emirates (UAE)', 'الإمارات العربية المتحدة (UAE)', 'Emirati', 'الإماراتي'),
            (167, 'United Kingdom (UK)', 'المملكة المتحدة (UK)', 'British', 'البريطانيون'),
            (168, 'United States of America (USA)', 'الولايات المتحدة الأمريكية (USA)', 'US', 'الولايات المتحدة'),
            (169, 'Uruguay', 'أوروغواي', 'Uruguayan', 'عرفي'),
            (170, 'Uzbekistan', 'أوزبكستان', 'Uzbek', 'الأوزبكي'),
            (171, 'Vanuatu', 'فانواتو', 'Vanuatuan', 'فانواتو'),
            (173, 'Venezuela', 'فنزويلا', 'Venezuelan', 'الفنزويلي'),
            (174, 'Vietnam', 'فيتنام', 'Vietnamese', 'الفيتنامية'),
            (175, 'Wales', 'ويلز', 'Welsh', 'ويلزي'),
            (176, 'Western Samoa', 'ساموا الغربية', 'Western Samoan', 'الغربية ساموا'),
            (177, 'Yemen', 'يمني', 'Yemeni', 'يمني'),
            (178, 'Yugoslavia', 'يوغوسلافيا', 'Yugoslav', 'اليوغوسلافية'),
            (179, 'Zaire', 'زائير', 'Zaïrean', 'زائير'),
            (180, 'Zambia', 'زامبيا', 'Zambian', 'زامبيا'),
            (181, 'Zimbabwe', 'زيمبابوي', 'Zimbabwean', 'زيمبابوي'),
            (182, 'America', 'أمريكا', 'American', 'أمريكي'),
            (183, 'None', 'غير محددي الجنسية', 'None', 'غير محددي الجنسية'),
            (184, 'Palestine', 'فلسطين', 'Palestine', 'فلسطين')")->execute();
    }

    public function down()
    {
        echo "m170425_132300_country cannot be reverted.\n";

        return false;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
