<?php

namespace admin\models;

use Yii;


class StaffExpenses extends \common\models\StaffExpenses
{
    public function fields()
    {
        $field =  parent::fields(); // TODO: Change the autogenerated stub
        $field['categoryLbl'] = function ($model) {
            return $model->getCategory();
        };

        $field['statusLbl'] = function ($model) {
            return $model->getStatus();
        };

        return $field;
    }
}
