version: '3.8'

networks:
  studenthub-network:
    driver: bridge

services:
  
  mysql:
    image: mysql:9
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=studenthub
      - MYSQL_DATABASE=studenthub
      - MYSQL_USER=studenthubuser
      - MYSQL_PASSWORD=studenthub
    ports:
      - "3307:3306"
    networks:
      - studenthub-network

  app:
    build: 
      context: .
      dockerfile: ./Dockerfile-nginx-local
    container_name: studenthub-backend-local
    #command:
    #  - /bin/sh
    #  - -c
    #  - |
    #    sleep 5 && \
    #    ./init --env=Dev-Server --overwrite=All && \
    #    ./yii migrate && \
    #    sleep 1 && \
    #    ln -s /etc/nginx/sites-available/basic.conf /etc/nginx/sites-enabled/ && \
    #    service nginx restart  && \
    #    tail -f /dev/null  # Keep container running
    ports:
      - "8080:80" #app endpoint
      - "21080:21080" # admin app port
      - "22080:22080" # candidate app port
      - "23080:23080" # employer app port
      - "24080:24080" # inspector app port
      - "25080:25080" # staff app port
      - "26080:26080" # verification app port
      - "3001:3001" # Yeaster microservice todo
      - "3306:3306" # mysql port
    volumes:
      - .:/var/www/html
      #- ./nginx/basic.conf:/etc/nginx/sites-available/basic.conf
    depends_on:
      - redis
      - mysql
    networks:
      - studenthub-network

  redis:
    image: redis:6.2.3
    ports:
      - "7777:7777"
      - "6379:6379"
    networks:
      - studenthub-network
   # command:
   #   - redis-server --port 7777
    volumes:
    - redis-data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: studenthubuser
      PMA_PASSWORD: studenthub
    ports:
      - "8081:80"
    networks:
      - studenthub-network
    depends_on:
      - mysql

volumes:
  redis-data:
  mysql-data: 

