version: '3.8'

networks:
  studenthub-network:
    driver: bridge

services:
  app:
    build: .
    container_name: studenthub-backend
    command:
    #  - ./init --env=Krushn --overwrite=All
      - ./yii migrate

    ports:
      - "8080:80" #app endpoint
      - "3001:3001" # Yeaster microservice
      - "3306:3306" # mysql port
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - studenthub-network

  redis:
    image: redis:6.2.3
    ports:
      - "7777:7777"
    networks:
      - studenthub-network
    command:
      - redis-server --port 7777
    volumes:
      - redis-data:/data

volumes:
  redis-data:
