version: '3.8'

networks:
  studenthub-network:
    driver: bridge

services:
  app:
    build: .
    container_name: studenthub-backend
    command:
    #  - ./init --env=Krushn --overwrite=All
      - ./yii migrate
    #  - sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

    ports:
      - "8080:80" #app endpoint
      - "3001:3001" # Yeaster microservice
      - "3306:3306" # mysql port
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - studenthub-network

  redis:
    image: redis:6.2.3
    ports:
      - "7777:7777"
    networks:
      - studenthub-network
    command:
      - redis-server --port 7777
    volumes:
      - redis-data:/data

volumes:
  redis-data:
