<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\AttributeBehavior;
use yii\helpers\ArrayHelper;
use common\models\StoryActivity;
use common\models\Request;

/**
 * This is the model class for table "story".
 *
 * @property string $story_uuid
 * @property string $request_uuid
 * @property int $story_status
 * @property int $story_time_spent
 * @property string $story_created_at
 * @property string $story_last_updated_at
 *
 * @property Request $requestUu
 * @property StoryActivity[] $storyActivities
 */
class Story extends \yii\db\ActiveRecord
{

    const STATUS_UNSTARTED = 0;
    const STATUS_STARTED = 1;
    const STATUS_FINISHED = 2;
    const STATUS_DELIVERED = 3;
    const STATUS_REJECTED = 4;
    const STATUS_ACCEPTED = 5;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'story';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['story_uuid','request_uuid'], 'required'],
            ['story_status', 'in', 'range' => [self::STATUS_UNSTARTED, self::STATUS_STARTED, self::STATUS_FINISHED,self::STATUS_DELIVERED,self::STATUS_REJECTED,self::STATUS_ACCEPTED]],
            [['story_status', 'story_time_spent'], 'integer'],
            [['story_created_at', 'story_last_updated_at'], 'safe'],
            [['story_uuid', 'request_uuid'], 'string', 'max' => 60],
            [['story_uuid'], 'unique'],
            [['request_uuid'], 'exist', 'skipOnError' => true, 'targetClass' => Request::className(), 'targetAttribute' => ['request_uuid' => 'request_uuid']],
        ];
    }


    public function behaviors() {
        return [
            [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => 'story_uuid',
                ],
                'value' => function() {
                    if (!$this->story_uuid)
                        $this->story_uuid = 'story_' . Yii::$app->db->createCommand('SELECT uuid()')->queryScalar();

                    return $this->story_uuid;
                }
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'story_created_at',
                'updatedAtAttribute' => 'story_last_updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub


        if($insert){
          $storyActivity = new StoryActivity();
          $storyActivity->story_uuid = $this->story_uuid;
          $storyActivity->activity_status = Story::STATUS_UNSTARTED;
          $storyActivity->save(false);
        }

    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'story_uuid' => 'Story Uuid',
            'request_uuid' => 'Request Uuid',
            'story_status' => 'Story Status',
            'story_time_spent' => 'Story Time Spent',
            'story_created_at' => 'Story Created At',
            'story_last_updated_at' => 'Story Last Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequest()
    {
        return $this->hasOne(Request::className(), ['request_uuid' => 'request_uuid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoryActivities()
    {
        return $this->hasMany(StoryActivity::className(), ['story_uuid' => 'story_uuid']);
    }
}
