<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\AttributeBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "story_activity".
 *
 * @property string $story_activity_uuid
 * @property string $story_uuid
 * @property int $staff_id
 * @property int $activity_time_spent
 * @property int $activity_status
 * @property string $activity_created_at
 * @property string $activity_last_updated_at
 *
 * @property Staff $staff
 * @property Story $storyUu
 */
class StoryActivity extends \yii\db\ActiveRecord
{

    const STATUS_UNSTARTED = 0;
    const STATUS_STARTED = 1;
    const STATUS_FINISHED = 2;
    const STATUS_DELIVERED = 3;
    const STATUS_REJECTED = 4;
    const STATUS_ACCEPTED = 5;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'story_activity';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['story_uuid'], 'required'],
            ['activity_status', 'in', 'range' => [self::STATUS_UNSTARTED, self::STATUS_STARTED, self::STATUS_FINISHED,self::STATUS_DELIVERED,self::STATUS_REJECTED,self::STATUS_ACCEPTED]],
            [['staff_id', 'activity_time_spent', 'activity_status'], 'integer'],
            [['activity_last_updated_at','activity_created_at'], 'safe'],
            [['story_activity_uuid', 'story_uuid'], 'string', 'max' => 60],
            [['story_activity_uuid'], 'unique'],
            [['staff_id'], 'exist', 'skipOnError' => true, 'targetClass' => Staff::className(), 'targetAttribute' => ['staff_id' => 'staff_id']],
            [['story_uuid'], 'exist', 'skipOnError' => true, 'targetClass' => Story::className(), 'targetAttribute' => ['story_uuid' => 'story_uuid']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'story_activity_uuid' => 'Story Activity Uuid',
            'story_uuid' => 'Story Uuid',
            'staff_id' => 'Staff ID',
            'activity_time_spent' => 'Activity Time Spent',
            'activity_status' => 'Activity Status',
            'activity_created_at' => 'Activity Created At',
            'activity_last_updated_at' => 'Activity Datetime',
        ];
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $story_model = Story::findOne($this->story_uuid);

        if($this->staff_id)
          $story_model->staff_id = $this->staff_id;

        $story_model->story_status = $this->activity_status;
        $story_model->story_time_spent = $story_model->getStoryActivities()->sum('activity_time_spent');

        if($this->staff_id)
          $story_model->staff_id = $this->staff_id;
        else
          $story_model->staff_id = null;


        $story_model->save(false);

    }


    public function behaviors() {
        return [
            [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => 'story_activity_uuid',
                ],
                'value' => function() {
                    if (!$this->story_activity_uuid)
                        $this->story_activity_uuid = 'stry_act_' . Yii::$app->db->createCommand('SELECT uuid()')->queryScalar();

                    return $this->story_activity_uuid;
                }
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'activity_created_at',
                'updatedAtAttribute' => 'activity_last_updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaff()
    {
        return $this->hasOne(Staff::className(), ['staff_id' => 'staff_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStory()
    {
        return $this->hasOne(Story::className(), ['story_uuid' => 'story_uuid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequest()
    {
        return $this->hasOne(Request::className(), ['request_uuid' => 'request_uuid'])->via('story');
    }


        /**
         * @return \yii\db\ActiveQuery
         */
        public function getCompany($modelClass = "\common\models\Company")
        {
            return $this->hasOne($modelClass::className(), ['company_id' => 'company_id'])->via('request');
        }

}
