<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\AttributeBehavior;
use yii\db\Expression;

/**
 * User model
 *
 * @property integer $user_uuid
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class WalletUser extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_INACTIVE = 9;
    const STATUS_ACTIVE = 10;

    const EMAIL_VERIFIED = 1;
    const EMAIL_NOT_VERIFIED = 0;

    public $password;

    public static function getDb()
    {
        return \Yii::$app->walletDb;
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        //todo: add limit_email, new_email, email_verification
        //todo: unique username?
        //todo: add name?
        return [
            ['password', 'safe'],
            [['username', 'email', 'bank_uuid', 'bank_account_name', 'iban'], 'string'],
            ['auth_key', 'default', 'value' => ""],
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
            [['bank_uuid'], 'exist', 'skipOnError' => true, 'targetClass' => WalletBank::className(), 'targetAttribute' => ['bank_uuid' => 'bank_uuid']],
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => AttributeBehavior::className(),
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => 'user_uuid',
                ],
                'value' => function() {
                    if (!$this->user_uuid)
                        $this->user_uuid = 'user_' . Yii::$app->db->createCommand('SELECT uuid()')->queryScalar();

                    return $this->user_uuid;
                }
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function beforeSave($insert) {

        if ($this->password) {
            $this->setPassword($this->password);
        }

        return parent::beforeSave($insert);
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     * @return bool
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if (
            array_key_exists('iban', $changedAttributes) ||
            array_key_exists('bank_account_name', $changedAttributes) ||
            array_key_exists('bank_uuid', $changedAttributes)
        ) {
            //update bank details on all non paid transfers

            \common\models\WalletTransfer::updateAll([
                'bank_uuid' => $this->bank_uuid,
                'transfer_benef_name' => $this->bank_account_name,
                'transfer_benef_iban' => $this->iban
            ], [
                'transfer_status' => WalletTransfer::STATUS_INITIATED,
                'user_uuid' => $this->user_uuid
            ]);
        }

        return true;
    }

    /**
     * return wallet balance
     * @return string|null
     * @throws \yii\base\InvalidConfigException
     */
    public function getBalance($format = true)
    {
        $amount = BalanceAccount::getBalance($this->user_uuid,  "Payable_for_this_user_uuid");

        return $format? Yii::$app->formatter->asCurrency($amount): $amount;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['user_uuid' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        $token = UserToken::find()->where(['token_value' => $token])->with('user')->one();

        if($token){
            return $token->user;
        }
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByUnVerifiedToken($token, $type = null) {

        $token = UserToken::find()
            ->andWhere(['token_value' => $token])
            ->with('user')
            ->one();

        if ($token && $token->user && !$token->user->deleted) {
            return $token->user;
        }
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by email
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email) {

        $walletUser = static::findOne(['email' => $email]);

        if($walletUser)
            return $walletUser;

        // if no user add wallet user account

        $user = Candidate::findOne(['candidate_email' => $email]);

        $bank = null;

        if($user->bank) {
            $bank = WalletBank::findOne(['bank_iban_code' => $user->bank->bank_iban_code]);

            //add wallet bank if not

            if(!$bank) {
                $bank = new WalletBank;
                $bank->bank_name = $user->bank->bank_name;
                $bank->bank_iban_code = $user->bank->bank_iban_code;
                $bank->bank_swift_code = $user->bank->bank_swift_code;
                $bank->bank_address = $user->bank->bank_address;
                $bank->bank_transfer_type = $user->bank->bank_transfer_type;
                $bank->save();
            }
        }

        $walletUser = new WalletUser();
        $walletUser->username = $user->candidate_name;
        $walletUser->email = $user->candidate_email;
        $walletUser->password_hash = $user->candidate_password_hash;
        $walletUser->generateAuthKey();
        $walletUser->status = WalletUser::STATUS_ACTIVE;
        $walletUser->bank_uuid = $bank? $bank->bank_uuid: null;
        $walletUser->bank_account_name = $user->bank_account_name;
        $walletUser->iban = $user->candidate_iban;

        $walletUser->save();

        return $walletUser;
    }

    /**
     * Finds user by email
     * @param string $email
     * @return static|null
     */
    public static function findByAdminEmail($email) {

        $walletUser = static::findOne(['email' => $email]);

        if($walletUser)
            return $walletUser;

        // if no user add wallet user account

        $user = Admin::findOne(['admin_email' => $email]);

        $walletUser = new WalletUser();
        $walletUser->username = $user->admin_name;
        $walletUser->email = $user->admin_email;
        $walletUser->password_hash = $user->admin_password_hash;
        $walletUser->generateAuthKey();
        $walletUser->status = WalletUser::STATUS_ACTIVE;
        $walletUser->save();

        return $walletUser;
    }

    /**
     * Finds user by email
     * @param string $email
     * @return static|null
     */
    public static function findByContactEmail($email) {

        $walletUser = static::findOne(['email' => $email]);

        if($walletUser)
           return $walletUser;

        // if no user add wallet user account

        $user = Contact::findOne(['contact_email' => $email]);

            $walletUser = new WalletUser();
            $walletUser->username = $user->contact_name;
            $walletUser->email = $user->contact_email;
            $walletUser->password_hash = $user->contact_password_hash;
            $walletUser->generateAuthKey();
            $walletUser->status = WalletUser::STATUS_ACTIVE;
            $walletUser->save();

            return $walletUser;
    }

    public function getBalanceAccount() {

        $account = BalanceAccount::find()
            ->andWhere([
                'account_uuid' => $this->user_uuid,
                'type' => BalanceAccount::TYPE_USER_PAYABLE
            ])
            ->one();

        if (!$account) {
            $account = new BalanceAccount();
            $account->account_uuid = $this->user_uuid;
            $account->type = BalanceAccount::TYPE_USER_PAYABLE;
            $account->save();
        }

        return $account;
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * Create an Access Token Record for this User
     * if the user user already has one, it will return it instead
     * @return \common\models\UserToken
     */
    public function getAccessToken()
    {
        // Return existing inactive token if found

        $token = UserToken::findOne([
            'user_uuid' => $this->user_uuid,
            'token_status' => self::STATUS_ACTIVE
        ]);

        if($token){
            return $token;
        }

        // Create new inactive token

        $token = new UserToken();
        $token->user_uuid = $this->user_uuid;
        $token->token_value = UserToken::generateUniqueTokenString();
        $token->token_status = UserToken::STATUS_ACTIVE;
        $token->save(false);

        return $token;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransfers($modelClass = "\common\models\WalletTransfer")
    {
        return $this->hasMany($modelClass::className(), ['user_uuid' => 'user_uuid']);
    }
}
