<?php
/**
 * The manifest of files that are local to specific environment.
 * This file returns a list of environments that the application
 * may be installed under. The returned data must be in the following
 * format:
 *
 * ```php
 * return [
 *     'environment name' => [
 *         'path' => 'directory storing the local files',
 *         'skipFiles'  => [
 *             // list of files that should only copied once and skipped if they already exist
 *         ],
 *         'setWritable' => [
 *             // list of directories that should be set writable
 *         ],
 *         'setExecutable' => [
 *             // list of files that should be set executable
 *         ],
 *         'setCookieValidationKey' => [
 *             // list of config files that need to be inserted with automatically generated cookie validation keys
 *         ],
 *         'createSymlink' => [
 *             // list of symlinks to be created. Keys are symlinks, and values are the targets.
 *         ],
 *     ],
 * ];
 * ```
 */
return [
    'Krushn' => [
        'path' => 'krushn',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
            'verification/config/main-local.php',
        ],
    ],

    'Krushn-Nginx' => [
        'path' => 'krushn-nginx',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
            'verification/config/main-local.php',
        ],
    ],

    'Development' => [
        'path' => 'dev',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],

    'Dev-Server' => [
        'path' => 'dev-server',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Dev-Server-Railway' => [
        'path' => 'dev-server-railway',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
            'deployment.sh',
            'deployments/'
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Dev-Server-Nginx' => [
        'path' => 'dev-server-nginx',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Dev-Server-Nginx-Debug' => [
        'path' => 'dev-server-nginx-debug',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Circle-CI' => [
        'path' => 'circle-ci',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Production' => [
        'path' => 'prod',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Production-Nginx' => [
        'path' => 'prod-nginx',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
    'Production-Railway' => [
        'path' => 'prod-railway',
        'setWritable' => [
            'admin/runtime',
            'admin/web/assets',
            'candidate/runtime',
            'candidate/web/assets',
            'company/runtime',
            'company/web/assets',
            'manager/runtime',
            'manager/web/assets',
            'staff/runtime',
            'staff/web/assets',
            'verification/runtime',
            'verification/web/assets',
            'inspector/runtime',
            'inspector/web/assets',
            'status/runtime',
            'status/web/assets',
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'admin/config/main-local.php',
            'candidate/config/main-local.php',
            'company/config/main-local.php',
            'manager/config/main-local.php',
            'staff/config/main-local.php',
            'verification/config/main-local.php',
            'inspector/config/main-local.php',
            'status/config/main-local.php',
        ],
    ],
];

