# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
    docker:
      # specify the version you desire here
      - image: circleci/php:7.4-apache-node-browsers

    #older: 7.3-apache-stretch-node-browsers

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: payroll_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        command:
            mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true

    # Specify Server Type. Keep it as small as possible to reduce costs
    resource_class: small

    working_directory: ~/studenthub

    steps:
      - checkout

      - run:
          name: Install things we need
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev libmcrypt-dev libreadline-dev zip zlib1g-dev default-mysql-client

      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install gd
            sudo apt-get install
            sudo docker-php-ext-install pdo_mysql && sudo docker-php-ext-enable pdo_mysql
        # sudo docker-php-ext-configure intl
        # sudo docker-php-ext-install intl

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Initialize Dev Environment
          command: ./init --env=Circle-CI --overwrite=All

      - run:
          name: Install DB Migrations
          command: ./yii_test migrate --interactive=0


      #---------- staff app --------------#

      - run:
          name: Run Staff app Codeception functional tests and store result output
          command: cd ./staff && ../vendor/bin/codecept run functional --xml --html --fail-fast

      - run:
         name: Run Staff app Codeception tests and store result output
         command: ./vendor/bin/codecept run staff/tests/unit --xml --html --fail-fast

      #---------- company app --------------#

      - run:
          name: Run Company app Codeception functional tests and store result output
          command: cd ./company && ../vendor/bin/codecept run functional --xml --html --fail-fast

      - run:
         name: Run Company app Codeception tests and store result output
         command: ./vendor/bin/codecept run company/tests/unit --xml --html --fail-fast

      #---------- admin app --------------#

      - run:
          name: Run Admin app Codeception functional tests and store result output
          command: cd ./admin && ../vendor/bin/codecept run functional --xml --html --fail-fast

      - run:
         name: Run Codeception tests and store result output
         command: cd ./admin && ../vendor/bin/codecept run unit --xml --html --fail-fast

      #---------- candidate app --------------#

      - run:
          name: Run User app Codeception functional tests and store result output
          command: cd ./candidate && ../vendor/bin/codecept run functional --xml --html --fail-fast

      - run:
         name: Run Candidate app Codeception unit tests and store result output
         command: cd ./candidate && ../vendor/bin/codecept run unit --xml --html --fail-fast

      #---------- common --------------#

      - run:
          name: Run Codeception tests and store result output
          command: cd ./common && ../vendor/bin/codecept run unit --xml --html --fail-fast

      - store_test_results:
         path: ~/tamr/console/runtime/logs

      - store_artifacts:
         path: ~/tamr/console/runtime/logs/report.html
         destination: report
