<?php

return [
    [
        'candidate_id' => 1,
        'candidate_uid' => 'lwNvdBaW1gPY__vSeEtF',
        'store_id' => 1,
        'bank_id' => 1,
        'university_id' => 1,
        'country_id' => 1,
        'bank_account_name' => 'Akshay Bhatia',
        'candidate_iban' => 'IBAN123456',
        'candidate_name' => 'Akshay Bhatia',
        'candidate_name_ar' => 'أكشاي باتيا',
        'candidate_personal_photo' => 'photos/photo-1497874516406.png',
        'candidate_email' => 'candidate1@bawes.net',
        'candidate_phone' => 989898989898,
        'candidate_address_line1' => '106, BHAYLI CANAL RD',
        'candidate_birth_date' => '1992-11-11',
        'candidate_civil_id' => 'XIS1212121',
        'candidate_civil_expiry_date' => date('Y-m-d', strtotime('+1 month')),
        'candidate_civil_photo_front' => 'photos/photo-1497874516406.png',
        'candidate_civil_photo_back' => 'photos/photo-1497874516406.png',
        'candidate_hourly_rate' => 1.7,
        'candidate_auth_key' => 'TnO9eI-XGIxeJGH7n57xSMyJfZ-5NKo6',
        'candidate_password_hash' => \Yii::$app->getSecurity()->generatePasswordHash('123456'),
        'candidate_password_reset_token' => NULL,
        'candidate_status' => 1,
        'approved' => 1,
        'candidate_created_at' => '2017-02-23 19:53:20',
        'candidate_updated_at' => '2017-02-23 19:53:20'
    ],
    [
        'candidate_id' => 2,
        'candidate_uid' => 'O-o5uGjU_yh3ic2-Q99A',
        'store_id' => 1,
        'bank_id' => 1,
        'university_id' => 1,
        'country_id' => 1,
        'bank_account_name' => 'Sarika Dave',
        'candidate_iban' => 'IBAN123456',
        'candidate_name' => 'Sarika Dave',
        'candidate_name_ar' => 'ساريكا ديف',
        'candidate_personal_photo' => 'photos/photo-1497874516406.png',
        'candidate_email' => 'sarika@bawes.net',
        'candidate_phone' => 989898989898,
        'candidate_address_line1' => '106, BHAYLI CANAL RD',
        'candidate_birth_date' => '1992-11-11',
        'candidate_civil_id' => 'XIS1212122',
        'candidate_civil_expiry_date' => date('Y-m-d', strtotime('+1 month')),
        'candidate_civil_photo_front' => 'photos/photo-1497874516406.png',
        'candidate_civil_photo_back' => 'photos/photo-1497874516406.png',
        'candidate_hourly_rate' => 1.5,
        'candidate_auth_key' => 'TnO9eI-XGIxeJGH7n57xSMyJfZ-5NKo6',
        'candidate_password_hash' => \Yii::$app->getSecurity()->generatePasswordHash('123456'),
        'candidate_password_reset_token' => NULL,
        'candidate_status' => 1,
        'approved' => 1,
        'candidate_created_at' => '2017-02-23 19:53:20',
        'candidate_updated_at' => '2017-02-23 19:53:20'
    ],
    [
        'candidate_id' => 3,
        'candidate_uid' => 'O-123GjU_yh3ic2-Q99A',
        'store_id' => 3,
        'bank_id' => 1,
        'university_id' => 1,
        'country_id' => 1,
        'bank_account_name' => 'Sarika Dave',
        'candidate_iban' => 'IBAN123456',
        'candidate_name' => 'Sarika Dave',
        'candidate_name_ar' => 'ساريكا ديف',
        'candidate_personal_photo' => 'photos/photo-1497874516406.png',
        'candidate_email' => 'jenelia@bawes.net',
        'candidate_phone' => 989898989898,
        'candidate_address_line1' => '106, BHAYLI CANAL RD',
        'candidate_birth_date' => '1992-11-11',
        'candidate_civil_id' => 'XIS1212123',
        'candidate_civil_expiry_date' => date('Y-m-d', strtotime('+1 month')),
        'candidate_civil_photo_front' => 'photos/photo-1497874516406.png',
        'candidate_civil_photo_back' => 'photos/photo-1497874516406.png',
        'candidate_hourly_rate' => 1.5,
        'candidate_auth_key' => 'TnO9eI-XGIxeJGH7n57xSMyJfZ-5NKo6',
        'candidate_password_hash' => \Yii::$app->getSecurity()->generatePasswordHash('123456'),
        'candidate_password_reset_token' => NULL,
        'candidate_status' => 1,
        'approved' => 1,
        'candidate_created_at' => '2017-02-23 19:53:20',
        'candidate_updated_at' => '2017-02-23 19:53:20'
    ],
    [
        'candidate_id' => 4,
        'candidate_uid' => 'O-o5uGjU_893ic2-Q99A',
        'store_id' => 3,
        'bank_id' => 1,
        'university_id' => 1,
        'country_id' => 1,
        'bank_account_name' => 'Sarika Dave',
        'candidate_iban' => 'IBAN123456',
        'candidate_name' => 'Sarika Dave',
        'candidate_name_ar' => 'ساريكا ديف',
        'candidate_personal_photo' => 'photos/photo-1497874516406.png',
        'candidate_email' => 'andru@bawes.net',
        'candidate_phone' => 989898989898,
        'candidate_address_line1' => '106, BHAYLI CANAL RD',
        'candidate_birth_date' => '1992-11-11',
        'candidate_civil_id' => 'XIS1212124',
        'candidate_civil_expiry_date' => date('Y-m-d', strtotime('+1 month')),
        'candidate_civil_photo_front' => 'photos/photo-1497874516406.png',
        'candidate_civil_photo_back' => 'photos/photo-1497874516406.png',
        'candidate_hourly_rate' => 1.5,
        'candidate_auth_key' => 'TnO9eI-XGIxeJGH7n57xSMyJfZ-5NKo6',
        'candidate_password_hash' => \Yii::$app->getSecurity()->generatePasswordHash('123456'),
        'candidate_password_reset_token' => NULL,
        'candidate_status' => 1,
        'approved' => 1,
        'candidate_created_at' => '2017-02-23 19:53:20',
        'candidate_updated_at' => '2017-02-23 19:53:20'
    ]
];