<?php

return [
    //transfer #1
    [
    	'tc_id' => 1,
    	'transfer_id' => '1',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 2,
        'transfer_id' => '1',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #3
    [
    	'tc_id' => 3,
    	'transfer_id' => '3',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 4,
        'transfer_id' => '3',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #5 
    [
    	'tc_id' => 5,
    	'transfer_id' => '5',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 6,
        'transfer_id' => '5',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #7 
    [
    	'tc_id' => 7,
    	'transfer_id' => '7',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 8,
        'transfer_id' => '7',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #9 
    [
    	'tc_id' => 9,
    	'transfer_id' => '9',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 10,
        'transfer_id' => '9',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #11
    [
    	'tc_id' => 11,
    	'transfer_id' => '11',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => 12,
        'transfer_id' => '11',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
];