<?php

return [
    //transfer #1
    [
    	'tc_id' => '1',
    	'transfer_id' => '1',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '2',
        'transfer_id' => '1',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #3
    [
        'tc_id' => '3',
    	'transfer_id' => '3',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '4',
        'transfer_id' => '3',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #5 
    [
        'tc_id' => '5',
    	'transfer_id' => '5',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '6',
        'transfer_id' => '5',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #7 
    [
        'tc_id' => '7',
    	'transfer_id' => '7',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '8',
        'transfer_id' => '7',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #9 
    [
        'tc_id' => '9',
    	'transfer_id' => '9',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '10',
        'transfer_id' => '9',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #11
    [
        'tc_id' => '11',
    	'transfer_id' => '11',
    	'candidate_id' => '1',
    	'store_id' => '1',
    	'store_name' => 'First Store',
    	'company_id' => '2',
    	'company_name' => 'Second Company - Child',
    	'company_email' => 'company@company.com',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '12',
        'transfer_id' => '11',
        'candidate_id' => '2',
        'store_id' => '2',
        'store_name' => 'Second Store',
        'company_id' => '2',
        'company_name' => 'Second Company - Child',
        'company_email' => 'company@company.com',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #13
    [
        'tc_id' => '13',
    	'transfer_id' => '13',
    	'candidate_id' => '3',
    	'store_id' => '3',
    	'store_name' => 'Third Store - Without Child',
    	'company_id' => '3',
    	'company_name' => 'Without Child',
    	'company_email' => 'company3@bawes.net',
    	'candidate_hourly_rate' => '1.7',
    	'company_hourly_rate' => '2.0',
    	'hours' => 10,
    	'bonus' => 10,
    	'transfer_cost' => '0.350',
    	'paid' => 0,
    	'tc_created_at' => '2017-02-23 18:04:42',
    	'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '14',
        'transfer_id' => '13',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 20,
        'bonus' => 18,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #14
    [
        'tc_id' => '15',
        'transfer_id' => '14',
        'candidate_id' => '3',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '16',
        'transfer_id' => '14',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '17',
        'transfer_id' => '14',
        'candidate_id' => '5',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '18',
        'transfer_id' => '14',
        'candidate_id' => '6',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '19',
        'transfer_id' => '14',
        'candidate_id' => '7',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],

    //transfer #15
    [
        'tc_id' => '20',
        'transfer_id' => '15',
        'candidate_id' => '3',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '21',
        'transfer_id' => '15',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '22',
        'transfer_id' => '15',
        'candidate_id' => '5',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '23',
        'transfer_id' => '15',
        'candidate_id' => '6',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '24',
        'transfer_id' => '15',
        'candidate_id' => '7',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    //transfer #16
    [
        'tc_id' => '25',
        'transfer_id' => '16',
        'candidate_id' => '3',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '26',
        'transfer_id' => '16',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '27',
        'transfer_id' => '16',
        'candidate_id' => '5',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '28',
        'transfer_id' => '16',
        'candidate_id' => '6',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '29',
        'transfer_id' => '16',
        'candidate_id' => '7',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],

    //transfer #17
    [
        'tc_id' => '30',
        'transfer_id' => '17',
        'candidate_id' => '3',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '31',
        'transfer_id' => '17',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '32',
        'transfer_id' => '17',
        'candidate_id' => '5',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '33',
        'transfer_id' => '17',
        'candidate_id' => '6',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 0,
        'bonus' => 0,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '34',
        'transfer_id' => '17',
        'candidate_id' => '7',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
        
    //transfer #18
    [
        'tc_id' => '35',
        'transfer_id' => '18',
        'candidate_id' => '3',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '36',
        'transfer_id' => '18',
        'candidate_id' => '4',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '37',
        'transfer_id' => '18',
        'candidate_id' => '5',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '38',
        'transfer_id' => '18',
        'candidate_id' => '6',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 0,
        'bonus' => 0,
        'transfer_cost' => '0.350',
        'paid' => 1,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
    [
        'tc_id' => '39',
        'transfer_id' => '18',
        'candidate_id' => '7',
        'store_id' => '3',
        'store_name' => 'Third Store - Without Child',
        'company_id' => '3',
        'company_name' => 'Without Child',
        'company_email' => 'company3@bawes.net',
        'candidate_hourly_rate' => '1.5',
        'company_hourly_rate' => '2.0',
        'hours' => 10000,
        'bonus' => 10000,
        'transfer_cost' => '0.350',
        'paid' => 0,
        'tc_created_at' => '2017-02-23 18:04:42',
        'tc_updated_at' => '2017-02-23 18:04:42'
    ],
];