server {
    listen 80;
    server_name localhost 127.0.0.1;

    include php.conf;

    root /var/www/html;
}

server {
    listen 21080;
    server_name localhost 127.0.0.1 admin.studenthub.local;

    include php.conf;

    root /var/www/html/admin/web;
}

server {
    listen 22080;
    server_name localhost 127.0.0.1 student.studenthub.local;

    include php.conf;

    root /var/www/html/candidate/web;
}

server {
    listen 23080;
    server_name localhost 127.0.0.1 employer.studenthub.local;

    include php.conf;

    root /var/www/html/company/web;
}

server {
    listen 24080;
    server_name localhost 127.0.0.1 inspector.studenthub.local;

    include php.conf;

    root /var/www/html/inspector/web;
}

server {
    listen 25080;
    server_name localhost 127.0.0.1 staff.studenthub.local;

    include php.conf;

    root /var/www/html/staff/web;
}

server {
    listen 26080;
    server_name localhost 127.0.0.1 v.studenthub.local;

    include php.conf;

    root /var/www/html/verification/web;
}