index index.php index.html index.htm;

# Yii-specific configuration
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

location ~ \.(js|css|png|jpg|jpeg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
    try_files $uri =404;
}

# PHP handling
location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass app:9000;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    include fastcgi_params;
}

# Deny access to hidden files
location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
}