server {
    listen      80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return      404;
}

server {
    listen 80;
    listen [::]:80;
    server_name admin.api.dev.studenthub.co;

    include php.conf;

    root /var/www/html/admin/web;
}

server {
    listen 80;
    listen [::]:80;
    server_name student.api.dev.studenthub.co;

    include php.conf;

    root /var/www/html/candidate/web;
}

server {
    listen 80;
    server_name employer.api.dev.studenthub.co;

    include php.conf;

    root /var/www/html/company/web;
}

server {
    listen 80;
    listen [::]:80;
    server_name inspector.api.dev.studenthub.co;

    include php.conf;

    root /var/www/html/inspector/web;
}

server {
    listen 80;
    listen [::]:80;
    server_name staff.api.dev.studenthub.co;

    include php.conf;

    root /var/www/html/staff/web;
}

server {
    listen 80;
    listen [::]:80;
    server_name verification.dev.studenthub.co;

    include php.conf;

    root /var/www/html/verification/web;
}

server {
    listen 80;
    listen [::]:80;
    server_name v.dev.studenthub.co;

    include php.conf;

    root /var/www/html/verification/web;
}
